name = "dinstack-api"
main = "worker.ts"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

# ------------------------------------------------------------------------------------------------------------

[[env.local.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'dinstack-public-local'

# ------------------------------------------------------------------------------------------------------------

# [env.preview.route]
# pattern = "preview.api.example.com"
# custom_domain = true

[[env.preview.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'dinstack-public-preview'

# ------------------------------------------------------------------------------------------------------------

[env.production]
logpush = true

# [env.production.route]
# pattern = "api.example.com"
# custom_domain = true

[[env.production.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'dinstack-public-production'

# ------------------------------------------------------------------------------------------------------------
