name = "dinstack-api"
main = "worker.ts"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

# ------------------------------------------------------------------------------------------------------------

[env.local.vars]
WORKER_ENV = "development"
WEB_URL = "http://localhost:3000"

# ------------------------------------------------------------------------------------------------------------

# [env.preview.route]
# pattern = "preview.api.example.com"
# custom_domain = true

[env.preview.vars]
WORKER_ENV = "development"
WEB_URL = "https://preview.example.com"

# ------------------------------------------------------------------------------------------------------------

[env.production]
logpush = true

# [env.production.route]
# pattern = "api.example.com"
# custom_domain = true

[env.production.vars]
WORKER_ENV = "production"
WEB_URL = "https://app.example.com"

# ------------------------------------------------------------------------------------------------------------
