name = "dinstack-api"
main = "core/worker.ts"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

# ------------------------------------------------------------------------------------------------------------

[env.local.vars]
WORKER_ENV = "development"
WEB_URL = "http://localhost:3000"
GOOGLE_REDIRECT_URL = "http://localhost:3000/oauth/google/callback"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"

[[env.local.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'dinstack-public-local'

# ------------------------------------------------------------------------------------------------------------

# [env.preview.route]
# pattern = "preview.api.example.com"
# custom_domain = true

[env.preview.vars]
WORKER_ENV = "development"
WEB_URL = "https://preview.example.com"
GOOGLE_REDIRECT_URL = "https://preview.example.com/oauth/google/callback"

[[env.preview.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'dinstack-public-preview'

# ------------------------------------------------------------------------------------------------------------

[env.production]
logpush = true

# [env.production.route]
# pattern = "api.example.com"
# custom_domain = true

[env.production.vars]
WORKER_ENV = "production"
WEB_URL = "https://example.com"
GOOGLE_REDIRECT_URL = "https://example.com/oauth/google/callback"

[[env.production.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'dinstack-public-production'

# ------------------------------------------------------------------------------------------------------------
