name: Deploy preview

on:
  pull_request:
    branches: [main]

jobs:
  deploy-preview:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm run lint

      - run: pnpm run typecheck

      - run: pnpm run --filter @dinstack/api db:migrate

      - run: pnpm run deploy:preview
